name: weather_app
description: "A minimal example for clean architecture and test-driven development."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  http: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
